### ISSUE TITLE
Execute Code Error: Xrm is not definied (XrmToolBox)

### ISSUE THREAD

**Issue by arth78** [GuidoPreite/DRB#12]
Hello,

When using DRB on XrmToolBox, I get an error when I try to execute the request (Xrm.WebApi method) from Code Editor: 
"Execute Code Error: Xrm is not definied" https://i.imgur.com/mmg45Mn.png

However, It works with XHR requests.

Regards,

**Comment by GuidoPreite** [comment]
That error is expected when running DRB inside XrmToolBox. there is a message inside the Xrm.WebApi tab:

NOTE: Xrm.WebApi is not available when DRB is executed inside XrmToolBox

Executing Xrm.WebApi requests is supported only inside the Managed Solution version, because the methods can be executed only inside that context.
