### ISSUE TITLE
OnPremise version connections are unsuported in XrmToolbox?

### ISSUE THREAD

**Issue by FixRM** [GuidoPreite/DRB#19]
Hello, thanks for the look. I'm trying to run tool against OnPremise connection and it tells that "current connection is not compatible". What is the reason of that?

**Comment by GuidoPreite** [comment]
@FixRM the XrmToolBox version of Dataverse REST Builder uses the Access Token in order to connect, the Access Token (as far as I know) is returned only for online connections.
If you need to use Dataverse REST Builder for an OnPremise instance, you can install the Managed Solution version.
Let me know if this solve your issue.

**Comment by FixRM** [comment]
Not really, but thanks.
